name: CI/CD for Market Web App

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Create package.json
      run: |
        cat <<EOF > package.json
        {
          "name": "market-web-app",
          "version": "1.0.0",
          "scripts": {
            "test": "echo \\"No tests specified\\" && exit 0",
            "build": "echo \\"Building project...\\" && exit 0"
          },
          "dependencies": {
            "firebase-tools": "^9.16.0"
          }
        }
        EOF

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


